// Generates supabase/seed.sql from src/data/cases/*.json
// Usage: npm run seed
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'src/data/cases');
const q = (v) => (v === undefined || v === null ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => (v === undefined || v === null ? 'null' : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`);

const CATS = {
  'pre-anesthesia': 'PRE-ANESTHESIA', airway: 'AIRWAY', monitoring: 'MONITORING', preparation: 'PREPARATION',
  intraoperative: 'INTRAOPERATIVE', 'post-anesthesia': 'POST-ANESTHESIA', emergency: 'EMERGENCY',
};
const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
const cases = files.map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')));
const out = ['-- GENERATED by scripts/generate-seed.mjs. Do not edit by hand. Safe to re-run (upserts).', 'begin;'];

Object.entries(CATS).forEach(([id, label], i) =>
  out.push(`insert into public.categories (id,label,sort) values (${q(id)},${q(label)},${i}) on conflict (id) do update set label=excluded.label, sort=excluded.sort;`));

const KEYS = ['type', 'title', 'tag', 'situation', 'prompt', 'critical', 'remedial', 'vitals', 'revealHistory', 'explanation', 'takeaway'];
for (const c of cases) {
  out.push(`insert into public.cases (id,number,title,category,difficulty,duration_min,summary,scenario,objectives,patient,vitals,history,"references",scoring,published) values (${q(c.id)},${c.number},${q(c.title)},${q(c.category)},${q(c.difficulty)},${c.durationMin},${q(c.summary)},${q(c.scenario)},${j(c.objectives)},${j(c.patient)},${j(c.vitals)},${j(c.history)},${j(c.references ?? [])},${j(c.scoring)},true)
on conflict (id) do update set number=excluded.number,title=excluded.title,category=excluded.category,difficulty=excluded.difficulty,duration_min=excluded.duration_min,summary=excluded.summary,scenario=excluded.scenario,objectives=excluded.objectives,patient=excluded.patient,vitals=excluded.vitals,history=excluded.history,"references"=excluded."references",scoring=excluded.scoring;`);
  c.steps.forEach((s, pos) => {
    out.push(`insert into public.case_steps (case_id,step_key,position,type,title,situation,prompt,tag,critical,remedial,vitals,reveal_history,explanation,takeaway) values (${q(c.id)},${q(s.id)},${pos},${q(s.type)},${q(s.title)},${q(s.situation)},${q(s.prompt)},${q(s.tag)},${Boolean(s.critical)},${Boolean(s.remedial)},${j(s.vitals)},${j(s.revealHistory)},${q(s.explanation)},${q(s.takeaway)})
on conflict (case_id,step_key) do update set position=excluded.position,type=excluded.type,title=excluded.title,situation=excluded.situation,prompt=excluded.prompt,tag=excluded.tag,critical=excluded.critical,remedial=excluded.remedial,vitals=excluded.vitals,reveal_history=excluded.reveal_history,explanation=excluded.explanation,takeaway=excluded.takeaway;`);
    const payload = Object.fromEntries(Object.entries(s).filter(([k]) => !KEYS.includes(k) && k !== 'id'));
    out.push(`insert into public.questions (step_id,payload) select id, ${j(payload)} from public.case_steps where case_id=${q(c.id)} and step_key=${q(s.id)}
on conflict (step_id) do update set payload=excluded.payload;`);
  });
}
out.push('commit;');
writeFileSync(join(root, 'supabase/seed.sql'), out.join('\n') + '\n');
console.log(`supabase/seed.sql written: ${cases.length} cases, ${cases.reduce((n, c) => n + c.steps.length, 0)} steps`);
